MeltanoLabs/tap-postgres

.github/workflows/test.yml, meltano.yml, pyproject.toml
Goal here is for our tests to start passing again.
=> ci: Add Python 3.11, remove Python 3.7. Clean up meltano.yml

poetry.lock, pyproject.toml
Closes the 4 dependabot PR's without needing to do them sequentially. Maybe there's a better way to do this 🤷
=> chore: Dependency upgrades. Black, pre-commit, faker, and tox

poetry.lock
Originally complete just to remove types-requests. 
But other things wanted to update in the process
```
visch@DESKTOP-9BDPA9T:~/git/tap-postgres$ poetry update
Updating dependencies
Resolving dependencies... (5.1s)
Writing lock file
Package operations: 4 installs, 2 updates, 2 removals
• Removing types-requests (2.28.11.12)
• Removing types-urllib3 (1.26.25.5)
• Installing cachetools (5.3.0)
• Installing chardet (5.1.0)
• Installing colorama (0.4.6)
• Installing pyproject-api (1.5.0)
• Updating typing-extensions (4.4.0 -> 4.5.0)
• Updating tox (3.28.0 -> 4.4.5)
visch@DESKTOP-9BDPA9T:~/git/tap-postgres$ git status
```
=> chore: Poetry update deps

.github/workflows/release.yml, pyproject.toml
Closes #31 
@edgarrmondragon  Published a 0.0.0 "dummy" version to PyPi to get us going. Added MeltanoLabs as an owner (Pending invitation). Note I also resent the invite for `meltanolabs-target-postgres`. 
If we could get MeltanoLabs added to both repos we should be able to use OIDC and remove the Token requirement before merging.
=> feat: Dynamic Releases

.github/workflows/test.yml
Reverts MeltanoLabs/tap-postgres#119
CI now running pytest with the wrong python version and we're getting the same? issue here https://github.com/MeltanoLabs/tap-postgres/actions/runs/4851288228/jobs/8644990135?pr=113
=> ci: Revert  Odd issues in actions, swapping poetry to pipx to see if it helps"

tap_postgres/tap.py
Closes https://github.com/MeltanoLabs/tap-postgres/issues/135
=> fix: make tunnel settings optional

tap_postgres/tap.py
This syncs up the tap with the overrides from the hub https://hub.meltano.com/extractors/tap-postgres--meltanolabs/#sqlalchemy_url-setting.
We decided that sql alchemy url should be a password type by default since it includes user/pass and the example url was a bit hard to interpret without going to the docs because user/pass/dbname were all postgres.
=> chore: match hub overrides

tests/test_core.py
Checks that the schema for a `jsonb` column in postgres is represented by `object` in jsonschema.
=> test: Add a test for schemas of jsonb objects.

poetry.lock, pyproject.toml
The next release of the SDK adds support for SQLAlchemy 2.0 but this tap does not seem to support it yet.
=> fix: Constrain SQLAlchemy to <2

README.md, tap_postgres/client.py, tap_postgres/tap.py, tests/test_core.py
Makes use of config filter_schemas to only pull specified schemas, increasing performance and allowing users to sidestep permissions issues for schemas they don't have access to.
Closes #215
=> feat: Filter schemas based on user-provided config

README.md
Copied from: https://hub.meltano.com/extractors/tap-postgres/#batch_config-encoding-compression-setting
Closes #220
=> docs: Add batch config to README copied from Meltano Hub

tap_postgres/client.py
Closes https://github.com/MeltanoLabs/tap-postgres/issues/297
=> fix: Treat streams with `LOG_BASED` replication as unsorted

.gitignore, tests/settings.py, tests/test_core.py, tests/test_replication_key.py, tests/test_selected_columns_only.py
Dear Derek and Edgar,
first things first: Thank you so much for your excellent work on MeltanoLabs' `{tap,target}-postgres`. We have been able to build upon them at [^1][^2] without much ado.
We fear we can't contribute anything significant back for the time being, other than cosmetic changes, if you like them. In this spirit, this patch makes a humble start. It was derived from https://github.com/crate-workbench/meltano-tap-cratedb/pull/1, and pulls the database-specific configuration values into a `tests/settings.py` file, to make it easier to adjust them.
With kind regards,
Andreas.
[^1]: https://github.com/crate-workbench/meltano-tap-cratedb
[^2]: https://github.com/crate-workbench/meltano-target-cratedb
=> test: Slightly refactor fixed config values into `tests/settings.py`

tap_postgres/client.py
~This was fixed upstream in https://github.com/meltano/sdk/pull/1487, but this tap overrides `get_records`.~ 
I think https://github.com/meltano/sdk/pull/2094 is the only difference between the two implementations?
UPDATE: Using the private `._mapping` attribute makes me nervous so I opened https://github.com/meltano/sdk/pull/2095 and updated this PR.
=> fix: Use `.mappings()` in cursor, to get rows as mappings

.github/workflows/test.yml, docker-compose.yml
Remove the postgres service from `test.yml` and add an additional postgres container to `docker-compose.yml`.
Closes #317
=> feat: Switch from postgres service to compose

tap_postgres/client.py, tests/test_core.py
Modifies the schema for jsonb and json objects because using an empty schema was not previously function for all taps (ex: tap-csv).
Closes #303
=> feat: Object validation

tap_postgres/client.py, tests/test_log_based.py
Slack thread: https://meltano.slack.com/archives/C06A1MD6A6L/p1724619858505739
When using log based replication, the wal2json output for columns of array types returns a string encoded in sql format.
Ex: '{a,b}'
The records produced by the tap in this sutation fails the target schema validation, since the schema is of type array and the value is a string.
I included a test case for it. Please feel free to modify the PR, I am by no means a python developer.
Related:
- https://github.com/eulerto/wal2json/issues/221#issuecomment-1025143441
=> fix: use psycopg text array decoding in wal2json messages

README.md, tap_postgres/client.py, tap_postgres/tap.py, tests/test_core.py
To allow JSON and JSONB to be tapped as plain objects
See [this Slack thread](https://meltano.slack.com/archives/C069CQNHDNF/p1729784981090099) for context
=> feat: Add json_as_object option

.github/workflows/project_add.yml, .github/workflows/release.yml, .github/workflows/test.yml
This will help prevent attacks such as [this one](https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/).
Dependabot is able to update these versions automatically, and it will preserve the readable version comments.
=> chore: pin GitHub Actions versions to commit hashes

tap_postgres/client.py
The same logic was applied upstream in https://github.com/meltano/sdk/pull/2418.
=> refactor: Remove redundant `is_sorted` implementation
